#web端口
server:
  port: 8888

mediaserver:
  #流媒体服务端口
  port: 8866
  #版本号
  version: @project.version@
  #网络超时，15秒
  netTimeout: 15000000
  #读写超时，15秒
  readOrWriteTimeout: 15000000
  #保存录像切片目录
  #  path: d:/flv/ts
  #无人观看时是否自动关闭流
  autoClose: true
  #无人拉流观看持续多久自动关闭，1分钟
  noClientsDuration: 60000

spring:
  profiles:
    active: dev

